// AUTO-GENERATED by tools/gen_register.py — R_registerRoutines table
// for mtrx_cpu (candidate 4). Regenerate after adding/removing an R entry point.
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

extern "C" {
// forward decls of the registered entry points (defined in the metric/dispatch TUs)
void matrix_Cosine_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Cosine_distance_same_block_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_per_cell_pair_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_per_cell_pair_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_distance_same_block_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_per_cell_pair_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_per_cell_pair_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Kendall_distance_same_block_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_distance_same_block_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_per_cell_pair_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_per_cell_pair_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Pearson_distance_same_block_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_per_cell_pair_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_per_cell_pair_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Spearman_distance_same_block_cpu(void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_per_cell_pair_distance_different_blocks_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_per_cell_pair_distance_same_block_cpu(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
SEXP C_dense_block_cpu(SEXP, SEXP, SEXP, SEXP);
SEXP C_sparse_block_cpu(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
}

static const R_CMethodDef CEntries[] = {
    {"matrix_Cosine_distance_different_blocks_cpu", (DL_FUNC) &matrix_Cosine_distance_different_blocks_cpu, 6},
    {"matrix_Cosine_distance_same_block_cpu", (DL_FUNC) &matrix_Cosine_distance_same_block_cpu, 6},
    {"matrix_Cosine_sparse_distance_different_blocks_cpu", (DL_FUNC) &matrix_Cosine_sparse_distance_different_blocks_cpu, 12},
    {"matrix_Cosine_sparse_distance_same_block_cpu", (DL_FUNC) &matrix_Cosine_sparse_distance_same_block_cpu, 12},
    {"matrix_Cosine_sparse_per_cell_pair_distance_different_blocks_cpu", (DL_FUNC) &matrix_Cosine_sparse_per_cell_pair_distance_different_blocks_cpu, 12},
    {"matrix_Cosine_sparse_per_cell_pair_distance_same_block_cpu", (DL_FUNC) &matrix_Cosine_sparse_per_cell_pair_distance_same_block_cpu, 12},
    {"matrix_Euclidean_distance_different_blocks_cpu", (DL_FUNC) &matrix_Euclidean_distance_different_blocks_cpu, 6},
    {"matrix_Euclidean_distance_same_block_cpu", (DL_FUNC) &matrix_Euclidean_distance_same_block_cpu, 6},
    {"matrix_Euclidean_sparse_distance_different_blocks_cpu", (DL_FUNC) &matrix_Euclidean_sparse_distance_different_blocks_cpu, 12},
    {"matrix_Euclidean_sparse_distance_same_block_cpu", (DL_FUNC) &matrix_Euclidean_sparse_distance_same_block_cpu, 12},
    {"matrix_Euclidean_sparse_per_cell_pair_distance_different_blocks_cpu", (DL_FUNC) &matrix_Euclidean_sparse_per_cell_pair_distance_different_blocks_cpu, 12},
    {"matrix_Euclidean_sparse_per_cell_pair_distance_same_block_cpu", (DL_FUNC) &matrix_Euclidean_sparse_per_cell_pair_distance_same_block_cpu, 12},
    {"matrix_Kendall_distance_different_blocks_cpu", (DL_FUNC) &matrix_Kendall_distance_different_blocks_cpu, 6},
    {"matrix_Kendall_distance_same_block_cpu", (DL_FUNC) &matrix_Kendall_distance_same_block_cpu, 6},
    {"matrix_Kendall_sparse_distance_different_blocks_cpu", (DL_FUNC) &matrix_Kendall_sparse_distance_different_blocks_cpu, 12},
    {"matrix_Kendall_sparse_distance_same_block_cpu", (DL_FUNC) &matrix_Kendall_sparse_distance_same_block_cpu, 12},
    {"matrix_Kendall_sparse_per_cell_pair_distance_different_blocks_cpu", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_distance_different_blocks_cpu, 12},
    {"matrix_Kendall_sparse_per_cell_pair_distance_same_block_cpu", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_distance_same_block_cpu, 12},
    {"matrix_Manhattan_distance_different_blocks_cpu", (DL_FUNC) &matrix_Manhattan_distance_different_blocks_cpu, 6},
    {"matrix_Manhattan_distance_same_block_cpu", (DL_FUNC) &matrix_Manhattan_distance_same_block_cpu, 6},
    {"matrix_Manhattan_sparse_distance_different_blocks_cpu", (DL_FUNC) &matrix_Manhattan_sparse_distance_different_blocks_cpu, 12},
    {"matrix_Manhattan_sparse_distance_same_block_cpu", (DL_FUNC) &matrix_Manhattan_sparse_distance_same_block_cpu, 12},
    {"matrix_Manhattan_sparse_per_cell_pair_distance_different_blocks_cpu", (DL_FUNC) &matrix_Manhattan_sparse_per_cell_pair_distance_different_blocks_cpu, 12},
    {"matrix_Manhattan_sparse_per_cell_pair_distance_same_block_cpu", (DL_FUNC) &matrix_Manhattan_sparse_per_cell_pair_distance_same_block_cpu, 12},
    {"matrix_Pearson_distance_different_blocks_cpu", (DL_FUNC) &matrix_Pearson_distance_different_blocks_cpu, 6},
    {"matrix_Pearson_distance_same_block_cpu", (DL_FUNC) &matrix_Pearson_distance_same_block_cpu, 6},
    {"matrix_Pearson_sparse_distance_different_blocks_cpu", (DL_FUNC) &matrix_Pearson_sparse_distance_different_blocks_cpu, 12},
    {"matrix_Pearson_sparse_distance_same_block_cpu", (DL_FUNC) &matrix_Pearson_sparse_distance_same_block_cpu, 12},
    {"matrix_Pearson_sparse_per_cell_pair_distance_different_blocks_cpu", (DL_FUNC) &matrix_Pearson_sparse_per_cell_pair_distance_different_blocks_cpu, 12},
    {"matrix_Pearson_sparse_per_cell_pair_distance_same_block_cpu", (DL_FUNC) &matrix_Pearson_sparse_per_cell_pair_distance_same_block_cpu, 12},
    {"matrix_Spearman_distance_different_blocks_cpu", (DL_FUNC) &matrix_Spearman_distance_different_blocks_cpu, 6},
    {"matrix_Spearman_distance_same_block_cpu", (DL_FUNC) &matrix_Spearman_distance_same_block_cpu, 6},
    {"matrix_Spearman_sparse_distance_different_blocks_cpu", (DL_FUNC) &matrix_Spearman_sparse_distance_different_blocks_cpu, 12},
    {"matrix_Spearman_sparse_distance_same_block_cpu", (DL_FUNC) &matrix_Spearman_sparse_distance_same_block_cpu, 12},
    {"matrix_Spearman_sparse_per_cell_pair_distance_different_blocks_cpu", (DL_FUNC) &matrix_Spearman_sparse_per_cell_pair_distance_different_blocks_cpu, 12},
    {"matrix_Spearman_sparse_per_cell_pair_distance_same_block_cpu", (DL_FUNC) &matrix_Spearman_sparse_per_cell_pair_distance_same_block_cpu, 12},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"C_dense_block_cpu", (DL_FUNC) &C_dense_block_cpu, 4},
    {"C_sparse_block_cpu", (DL_FUNC) &C_sparse_block_cpu, 8},
    {NULL, NULL, 0}
};

extern "C" void R_init_mtrx_cpu(DllInfo* dll) {
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, TRUE);   // keep glue string-name .C/.Call working (candidate 4)
}
