// AUTO-GENERATED by tools/gen_register.py — R_registerRoutines table
// for mtrx (candidate 4). Regenerate after adding/removing an R entry point.
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

extern "C" {
// forward decls of the registered entry points (defined in the metric/dispatch TUs)
bool check_gpu(void);
void matrix_Cosine_distance_different_blocks(void*, void*, void*, void*, void*, void*);
void matrix_Cosine_distance_same_block(void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_per_cell_pair_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Cosine_sparse_per_cell_pair_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_distance_different_blocks(void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_distance_same_block(void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_per_cell_pair_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Euclidean_sparse_per_cell_pair_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_distance_different_blocks(void*, void*, void*, void*, void*, void*);
void matrix_Kendall_distance_same_block(void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_a_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_a_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_b0_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_b0_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_b_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_b_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_dispatch_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_dispatch_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_hybrid_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Kendall_sparse_per_cell_pair_hybrid_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_distance_different_blocks(void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_distance_same_block(void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_per_cell_pair_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Manhattan_sparse_per_cell_pair_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_distance_different_blocks(void*, void*, void*, void*, void*, void*);
void matrix_Pearson_distance_same_block(void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_per_cell_pair_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Pearson_sparse_per_cell_pair_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_distance_different_blocks(void*, void*, void*, void*, void*, void*);
void matrix_Spearman_distance_same_block(void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_per_cell_pair_distance_different_blocks(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
void matrix_Spearman_sparse_per_cell_pair_distance_same_block(void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*, void*);
SEXP C_dense_block(SEXP, SEXP, SEXP, SEXP);
SEXP C_dense_block_batched(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_kernel_us_get(void);
SEXP C_kernel_us_reset(void);
SEXP C_sparse_block(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_sparse_block_batched(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
}

static const R_CMethodDef CEntries[] = {
    {"check_gpu", (DL_FUNC) &check_gpu, 0},
    {"matrix_Cosine_distance_different_blocks", (DL_FUNC) &matrix_Cosine_distance_different_blocks, 6},
    {"matrix_Cosine_distance_same_block", (DL_FUNC) &matrix_Cosine_distance_same_block, 6},
    {"matrix_Cosine_sparse_distance_different_blocks", (DL_FUNC) &matrix_Cosine_sparse_distance_different_blocks, 12},
    {"matrix_Cosine_sparse_distance_same_block", (DL_FUNC) &matrix_Cosine_sparse_distance_same_block, 12},
    {"matrix_Cosine_sparse_per_cell_pair_distance_different_blocks", (DL_FUNC) &matrix_Cosine_sparse_per_cell_pair_distance_different_blocks, 12},
    {"matrix_Cosine_sparse_per_cell_pair_distance_same_block", (DL_FUNC) &matrix_Cosine_sparse_per_cell_pair_distance_same_block, 12},
    {"matrix_Euclidean_distance_different_blocks", (DL_FUNC) &matrix_Euclidean_distance_different_blocks, 6},
    {"matrix_Euclidean_distance_same_block", (DL_FUNC) &matrix_Euclidean_distance_same_block, 6},
    {"matrix_Euclidean_sparse_distance_different_blocks", (DL_FUNC) &matrix_Euclidean_sparse_distance_different_blocks, 12},
    {"matrix_Euclidean_sparse_distance_same_block", (DL_FUNC) &matrix_Euclidean_sparse_distance_same_block, 12},
    {"matrix_Euclidean_sparse_per_cell_pair_distance_different_blocks", (DL_FUNC) &matrix_Euclidean_sparse_per_cell_pair_distance_different_blocks, 12},
    {"matrix_Euclidean_sparse_per_cell_pair_distance_same_block", (DL_FUNC) &matrix_Euclidean_sparse_per_cell_pair_distance_same_block, 12},
    {"matrix_Kendall_distance_different_blocks", (DL_FUNC) &matrix_Kendall_distance_different_blocks, 6},
    {"matrix_Kendall_distance_same_block", (DL_FUNC) &matrix_Kendall_distance_same_block, 6},
    {"matrix_Kendall_sparse_distance_different_blocks", (DL_FUNC) &matrix_Kendall_sparse_distance_different_blocks, 12},
    {"matrix_Kendall_sparse_distance_same_block", (DL_FUNC) &matrix_Kendall_sparse_distance_same_block, 12},
    {"matrix_Kendall_sparse_per_cell_pair_a_distance_different_blocks", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_a_distance_different_blocks, 12},
    {"matrix_Kendall_sparse_per_cell_pair_a_distance_same_block", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_a_distance_same_block, 12},
    {"matrix_Kendall_sparse_per_cell_pair_b0_distance_different_blocks", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_b0_distance_different_blocks, 12},
    {"matrix_Kendall_sparse_per_cell_pair_b0_distance_same_block", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_b0_distance_same_block, 12},
    {"matrix_Kendall_sparse_per_cell_pair_b_distance_different_blocks", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_b_distance_different_blocks, 12},
    {"matrix_Kendall_sparse_per_cell_pair_b_distance_same_block", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_b_distance_same_block, 12},
    {"matrix_Kendall_sparse_per_cell_pair_dispatch_distance_different_blocks", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_dispatch_distance_different_blocks, 12},
    {"matrix_Kendall_sparse_per_cell_pair_dispatch_distance_same_block", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_dispatch_distance_same_block, 12},
    {"matrix_Kendall_sparse_per_cell_pair_distance_different_blocks", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_distance_different_blocks, 12},
    {"matrix_Kendall_sparse_per_cell_pair_distance_same_block", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_distance_same_block, 12},
    {"matrix_Kendall_sparse_per_cell_pair_hybrid_distance_different_blocks", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_hybrid_distance_different_blocks, 12},
    {"matrix_Kendall_sparse_per_cell_pair_hybrid_distance_same_block", (DL_FUNC) &matrix_Kendall_sparse_per_cell_pair_hybrid_distance_same_block, 12},
    {"matrix_Manhattan_distance_different_blocks", (DL_FUNC) &matrix_Manhattan_distance_different_blocks, 6},
    {"matrix_Manhattan_distance_same_block", (DL_FUNC) &matrix_Manhattan_distance_same_block, 6},
    {"matrix_Manhattan_sparse_distance_different_blocks", (DL_FUNC) &matrix_Manhattan_sparse_distance_different_blocks, 12},
    {"matrix_Manhattan_sparse_distance_same_block", (DL_FUNC) &matrix_Manhattan_sparse_distance_same_block, 12},
    {"matrix_Manhattan_sparse_per_cell_pair_distance_different_blocks", (DL_FUNC) &matrix_Manhattan_sparse_per_cell_pair_distance_different_blocks, 12},
    {"matrix_Manhattan_sparse_per_cell_pair_distance_same_block", (DL_FUNC) &matrix_Manhattan_sparse_per_cell_pair_distance_same_block, 12},
    {"matrix_Pearson_distance_different_blocks", (DL_FUNC) &matrix_Pearson_distance_different_blocks, 6},
    {"matrix_Pearson_distance_same_block", (DL_FUNC) &matrix_Pearson_distance_same_block, 6},
    {"matrix_Pearson_sparse_distance_different_blocks", (DL_FUNC) &matrix_Pearson_sparse_distance_different_blocks, 12},
    {"matrix_Pearson_sparse_distance_same_block", (DL_FUNC) &matrix_Pearson_sparse_distance_same_block, 12},
    {"matrix_Pearson_sparse_per_cell_pair_distance_different_blocks", (DL_FUNC) &matrix_Pearson_sparse_per_cell_pair_distance_different_blocks, 12},
    {"matrix_Pearson_sparse_per_cell_pair_distance_same_block", (DL_FUNC) &matrix_Pearson_sparse_per_cell_pair_distance_same_block, 12},
    {"matrix_Spearman_distance_different_blocks", (DL_FUNC) &matrix_Spearman_distance_different_blocks, 6},
    {"matrix_Spearman_distance_same_block", (DL_FUNC) &matrix_Spearman_distance_same_block, 6},
    {"matrix_Spearman_sparse_distance_different_blocks", (DL_FUNC) &matrix_Spearman_sparse_distance_different_blocks, 12},
    {"matrix_Spearman_sparse_distance_same_block", (DL_FUNC) &matrix_Spearman_sparse_distance_same_block, 12},
    {"matrix_Spearman_sparse_per_cell_pair_distance_different_blocks", (DL_FUNC) &matrix_Spearman_sparse_per_cell_pair_distance_different_blocks, 12},
    {"matrix_Spearman_sparse_per_cell_pair_distance_same_block", (DL_FUNC) &matrix_Spearman_sparse_per_cell_pair_distance_same_block, 12},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"C_dense_block", (DL_FUNC) &C_dense_block, 4},
    {"C_dense_block_batched", (DL_FUNC) &C_dense_block_batched, 6},
    {"C_kernel_us_get", (DL_FUNC) &C_kernel_us_get, 0},
    {"C_kernel_us_reset", (DL_FUNC) &C_kernel_us_reset, 0},
    {"C_sparse_block", (DL_FUNC) &C_sparse_block, 8},
    {"C_sparse_block_batched", (DL_FUNC) &C_sparse_block_batched, 9},
    {NULL, NULL, 0}
};

extern "C" void R_init_mtrx(DllInfo* dll) {
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, TRUE);   // keep glue string-name .C/.Call working (candidate 4)
}
